In [ ]:
import os
os.environ["TF_CPP_MIN_LOG_LEVEL"]="3"
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam, SGD
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

C:\Users\Ahsan\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [ ]:
df=pd.read_csv('hh.csv')


In [35]:
X=df[['Height']].values
y=df[['Weight']].values

In [36]:
y

array([[  28. ],
       [  28.1],
       [  28.2],
       [  28.3],
       [  28.4],
       [  28.5],
       [  35.2],
       [  37.6],
       [  40. ],
       [  42.6],
       [  44.9],
       [  47.6],
       [  49.9],
       [  52.6],
       [  54.9],
       [  57.6],
       [  59.9],
       [  62.6],
       [  64.8],
       [  67.6],
       [  69.8],
       [  72.6],
       [  74.8],
       [  77.5],
       [  79.8],
       [  82.5],
       [  84.8],
       [  87.5],
       [  89.8],
       [  92.5],
       [  94.8],
       [  97.5],
       [  99.8],
       [ 102.5],
       [ 104.8]])

In [37]:
model = Sequential()
model.add(layers.Dense(1, input_shape=(1,)))

NameError: name 'layers' is not defined

In [ ]:
model.summary()

In [ ]:
model.compile(Adam(lr=0.8), 'mean_squared_error')

In [ ]:
model.fit(X,y_true, epochs=40)

In [ ]:
y_pred=model.predict(X)

In [ ]:
df.plot(kind='scatter',
       x='Height',
       y='Weight', title='Weight and Height in adults')
plt.plot(X, y_pred, color='red', linewidth=3)

In [11]:
w,b=model.get_weights()

In [12]:
w

array([[ 7.81147623]], dtype=float32)

In [17]:
b

array([-347.89904785], dtype=float32)